# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b04a51e1b4e5d829e74586d78be8d213381bbdde44bd6f0ae2750cf2ff55cfff86ab82dbb14d22c083144039aa80625bc4a3dd7f1f63795ad6ca2f7baca3d8ff

test:
  secret_key_base: f718ce0b314d647ae5c652c563d252f300f649dc54b0b600e82113b9ed6a498c0a7bc64da2dc67cacfebaf0b5b978b3133d35ca2f1e304feeca1ace7414ad9c3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
